version: '3.8'

services:
  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=abderrahim
      - POSTGRES_PASSWORD=abderrahim13
      - POSTGRES_DB=TicketManagementDB

    ports:
      - "5432:5432"


  backend:
    build:
      context: ./TicketManagementAPI
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=TicketManagementDB;Username=abderrahim;Password=abderrahim13
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build:
      context: ./ticket-management-ui
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

