version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: abderrahim
      POSTGRES_PASSWORD: abderrahim13
      POSTGRES_DB: TicketManagementDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
